# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_match_name', models.CharField(default='', max_length=150)),
                ('on_date', models.DateTimeField()),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 7, 284271))),
                ('preview', models.CharField(default='', max_length=500)),
                ('para1', models.CharField(default='', max_length=800)),
                ('para2', models.CharField(default='', max_length=800)),
                ('para3', models.CharField(default='', max_length=800, null=True)),
                ('team1_des', models.CharField(default='', max_length=100, null=True)),
                ('team1', models.CharField(default='', max_length=600)),
                ('team2_des', models.CharField(default='', max_length=100)),
                ('team2', models.CharField(default='', max_length=600)),
                ('team3_des', models.CharField(default='', max_length=100)),
                ('team3', models.CharField(max_length=600, null=True)),
                ('team4', models.ImageField(default=None, null=True, upload_to='')),
                ('team5', models.ImageField(default=None, null=True, upload_to='')),
                ('conclusion', models.CharField(default='', max_length=450)),
                ('final_verdict', models.CharField(default='', max_length=400)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_match_name', models.CharField(default='', max_length=150)),
                ('on_date', models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 7, 285772))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 7, 285772))),
                ('preview', models.CharField(default='', max_length=500)),
                ('para1', models.CharField(default='', max_length=800)),
                ('para2', models.CharField(default='', max_length=800)),
                ('para3', models.CharField(default='', max_length=800, null=True)),
                ('team1_des', models.CharField(default='', max_length=100, null=True)),
                ('team1', models.CharField(default='', max_length=700)),
                ('team2_des', models.CharField(default='', max_length=100)),
                ('team2', models.CharField(default='', max_length=700)),
                ('team3_des', models.CharField(default='', max_length=100)),
                ('team3', models.CharField(max_length=700, null=True)),
                ('team4', models.ImageField(default=None, null=True, upload_to='')),
                ('team5', models.ImageField(default=None, null=True, upload_to='')),
                ('conclusion', models.CharField(default='', max_length=450)),
                ('final_verdict', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 7, 283770))),
                ('is_cricket', models.BooleanField(default=False)),
                ('is_football', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='football',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Tournament'),
        ),
        migrations.AddField(
            model_name='cricket',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Tournament'),
        ),
    ]
