# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 23, 480437)),
        ),
        migrations.AlterField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 23, 481938)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 23, 481938)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 23, 479936)),
        ),
    ]
