# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasyapp', '0002_auto_20170531_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
                ('reply', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=0)),
                ('activation_code', models.IntegerField(default=828167)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cricket',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 49, 835363)),
        ),
        migrations.AlterField(
            model_name='football',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 49, 836863)),
        ),
        migrations.AlterField(
            model_name='football',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 49, 836863)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 18, 58, 49, 834862)),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Tournament'),
        ),
        migrations.AddField(
            model_name='faq',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.Match'),
        ),
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyapp.UserProfile'),
        ),
    ]
